iWishApp/Controllers/AffirmationsController.cs
using iWishApp.Models;
using iWishApp.ViewModels;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using iWishApp.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace iWishApp.Controllers
{
    public class AffirmationsController : Controller



    {

        private ApplicationDbContext _context;
        public AffirmationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // start index //
        // view all affifrmation below//

        public IActionResult Index(string SearchString)
        {
            ViewBag.CurrentFilter = SearchString;
            var affirmations = from a in _context.Affirmations
                               select a;
           


            if (!String.IsNullOrEmpty(SearchString))
            {
                affirmations = affirmations.Where(a => a.Text.Contains(SearchString));
            }

            {
                return View(affirmations.ToList());

            }
            
        }


        //[Authorize]
        [HttpGet]
        public IActionResult Add()
        {//put a n empty add affirmations view model

            AddAffirmationsViewModel addAffirmationsViewModel = new AddAffirmationsViewModel();
            return View(addAffirmationsViewModel);
        }

        //[Authorize]
        [HttpPost]
        public IActionResult Add(AddAffirmationsViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                Affirmations affirmation = new Affirmations(viewModel.Text);
                _context.Affirmations.Add(affirmation);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        //[Authorize]
        [HttpGet]
        public IActionResult Delete()
        {
            ViewBag.affirmations = _context.Affirmations.ToList();

            return View();
        }

       
       //[Authorize]
       [HttpPost]
        public IActionResult Delete(int[] affirmationIds)
        {
            foreach (int affirmationid in affirmationIds)
            {
                Affirmations affirmation = _context.Affirmations.Find(affirmationid);

                if (affirmation != null)
                {
                    _context.Affirmations.Remove(affirmation);
                }
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }


}

iWishApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - iWishApp</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/iWishApp.styles.css" asp-append-version="true" />

    @*<----  Bootstrap Template fonts beloow --->*@

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <link rel="stylesheet" href="~/css/aos.css">

    <link rel="stylesheet" href="~/css/ionicons.min.css">

    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">

    @*<----- End Of Bootstrap template fonts ---->*@

    <script src="js/jquery.min.js"></script>
    <script src="js/jquery-migrate-3.0.1.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/jquery.waypoints.min.js"></script>
    <script src="js/jquery.stellar.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.magnific-popup.min.js"></script>
    <script src="js/aos.js"></script>
    <script src="js/jquery.animateNumber.min.js"></script>
    <script src="js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="js/google-map.js"></script>
    <script src="js/main.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/react@17.0.2/umd/react.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/react-dom@17.0.2/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/babel/standalone@7.15.8/babel.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/react-bootstrap@2.0.0/dist/react-bootstrap.min.js"></script>


</head>
<body>

    <header>
        @*<---- Nav bar ---->*@









        

            @*<div id="colorlib-page">
                <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
                <aside id="colorlib-aside" role="complementary" class="js-fullheight">
                    <nav id="colorlib-main-menu" role="navigation">
                        <ul>
                            <li class="colorlib-active"><a href="index.html">Home</a></li>
                            <li><a asp-controller="Affirmations" asp-action="Index">Affirmations</a></li>
                            <li><a href="travel.html">Travel</a></li>
                            <li><a href="about.html">About</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </nav>
                    </div>*@
                    @*<---- End of Nav bar ---->*@
    @*<div class="colorlib-footer"
                 <div class="container">
                     <div class="row">
                         <div class="col-md-12">
                             <h1 class="d-inline-block text-wrap" id="colorlib-logo" class="mb-4"><a href="index.html" style="background-image: url(images/bg_1.jpg);"> 444 <span>Affirmations<span></a></h1>
                             </div>
                         </div>
                          </div>*@

                             @*<div class="mb-4">
                    <h3>Add to Wishlist</h3>
                    <form action="#" class="colorlib-subscribe-form">
                        <div class="form-group d-flex">
                            <div class="icon"><span class="icon-paper-plane"></span></div>
                            <input type="text" class="form-control" placeholder="Enter Affirmations">
                        </div>
                    </form>
                    is license
                </div>
                <<p class="pfooter">
                     Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
                    Copyright &copy;
            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                     Link back to Colorlib can't be removed. Templated under CC BY 3.0.
                    </p>
                </div>
            </aside>*@
                             <!-- END COLORLIB-ASIDE -->


</header>
    @*<------------------------------------------------------------------------------------------------------------------------------------------------------------>*@
   



    @*<------------------------------------------------------------------------------------------------------------------------------------------------------------>*@
    <div class="container">
        @*<main role="main" class="pb-3">*@
        @RenderBody()
        @*</main>*@
    </div>

    @*<footer class="border-top footer text-muted" style="position:fixed;">
        <div class="container">
            &copy; 2023 - iManifest- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>